export const Images = {
  logo: require("./app/img_logo.png"),
  logo_simple: require("./app/img_logo_simple.png"),
  dark_mode: require("./app/img_dark_mode.png"),
  light_mode: require("./app/img_light_mode.png"),
  rounded: require("./app/img_rounded.png"),
  banner: require("./app/img_banner.png"),
  avatar: {
    gg: require("./app/img_gg.png"),
    apple: require("./app/img_apple.png"),
    avatar_01: require("./app/img_avatar_01.png"),
    avatar_02: require("./app/img_avatar_02.png"),
    avatar_03: require("./app/img_avatar_03.png"),
    avatar_04: require("./app/img_avatar_04.png"),
    avatar_05: require("./app/img_avatar_05.png"),
    avatar_06: require("./app/img_avatar_06.png"),
  },
  finance: {
    creditcard_01: require("./finance/img_creditcard_01.png"),
    creditcard_02: require("./finance/img_creditcard_02.png"),
    creditcard_03: require("./finance/img_creditcard_03.png"),
    leaves: require("./finance/img_leaves.png"),
    leaf: require("./finance/img_leaf.png"),
    line: require("./finance/img_line.png"),
    money_bag: require("./finance/img_money_bag.png"),
    paypall: require("./finance/img_paypall.png"),
    netflix: require("./finance/img_netflix.png"),
    mcdonalds: require("./finance/img_mcdonalds.png"),
    gym: require("./finance/img_gym.png"),
    gas: require("./finance/img_gas.png"),
    electricity: require("./finance/img_electricity.png"),
    apple: require("./finance/img_apple.png"),
    amazon: require("./finance/img_amazon.png"),
    prime: require("./finance/img_prime.png"),
    nike: require("./finance/img_nike.png"),
  },
};
